import type { DentalEntry } from './dental-types';

/** ~25 hardcoded records with realistic German dental practice data */
export const MOCK_DENTAL_ENTRIES: DentalEntry[] = [
    {
        kartei_id: 1001,
        entry_date: new Date('2024-01-08'),
        patient_id: 'P001',
        insurance_state: 'GKV',
        file_entry: 'Patient klagt über Zahnschmerzen im Bereich 36.',
        service: 'Beratung',
    },
    {
        kartei_id: 1002,
        entry_date: new Date('2024-01-15'),
        patient_id: 'P002',
        insurance_state: 'PKV',
        file_entry: 'Routinekontrolle ohne Befund.',
        service: 'Kontrolle',
    },
    {
        kartei_id: 1003,
        entry_date: new Date('2024-01-22'),
        patient_id: 'P003',
        insurance_state: 'GKV',
        file_entry: 'Professionelle Zahnreinigung durchgeführt.',
        service: 'PZR',
    },
    {
        kartei_id: 1004,
        entry_date: new Date('2024-02-05'),
        patient_id: 'P004',
        insurance_state: 'GKV',
        file_entry: 'Karies an Zahn 25, Komposit-Füllung gelegt.',
        service: 'Füllung',
    },
    {
        kartei_id: 1005,
        entry_date: new Date('2024-02-12'),
        patient_id: 'P005',
        insurance_state: 'PKV',
        file_entry: 'Röntgenaufnahme Zahn 47 wegen apikaler Aufhellung.',
        service: 'Röntgen',
    },
    {
        kartei_id: 1006,
        entry_date: new Date('2024-02-19'),
        patient_id: 'P001',
        insurance_state: 'GKV',
        file_entry: 'Extraktion Zahn 36 nach erfolgloser Wurzelbehandlung.',
        service: 'Extraktion',
    },
    {
        kartei_id: 1007,
        entry_date: new Date('2024-02-26'),
        patient_id: 'P006',
        insurance_state: 'GKV',
        file_entry: 'Keramik-Inlay an Zahn 15 eingegliedert.',
        service: 'Inlay',
    },
    {
        kartei_id: 1008,
        entry_date: new Date('2024-03-04'),
        patient_id: 'P007',
        insurance_state: 'PKV',
        file_entry: 'Halbjährliche Kontrolle, leichter Zahnstein.',
        service: 'Kontrolle',
    },
    {
        kartei_id: 1009,
        entry_date: new Date('2024-03-11'),
        patient_id: 'P008',
        insurance_state: 'GKV',
        file_entry: 'PZR nach längerer Pause.',
        service: 'PZR',
    },
    {
        kartei_id: 1010,
        entry_date: new Date('2024-03-18'),
        patient_id: 'P009',
        insurance_state: 'PKV',
        file_entry: 'Beratung zu Implantaten nach Extraktion.',
        service: 'Beratung',
    },
    {
        kartei_id: 1011,
        entry_date: new Date('2024-03-25'),
        patient_id: 'P010',
        insurance_state: 'GKV',
        file_entry: 'Amalgam-Füllung an Zahn 46 erneuert.',
        service: 'Füllung',
    },
    {
        kartei_id: 1012,
        entry_date: new Date('2024-04-02'),
        patient_id: 'P002',
        insurance_state: 'PKV',
        file_entry: 'Röntgen Panorama zur Jahresvorsorge.',
        service: 'Röntgen',
    },
    {
        kartei_id: 1013,
        entry_date: new Date('2024-04-09'),
        patient_id: 'P003',
        insurance_state: 'GKV',
        file_entry: 'Extraktion Weisheitszahn 48.',
        service: 'Extraktion',
    },
    {
        kartei_id: 1014,
        entry_date: new Date('2024-04-16'),
        patient_id: 'P004',
        insurance_state: 'GKV',
        file_entry: 'Kontrolle nach Füllung, kein Befund.',
        service: 'Kontrolle',
    },
    {
        kartei_id: 1015,
        entry_date: new Date('2024-04-23'),
        patient_id: 'P005',
        insurance_state: 'PKV',
        file_entry: 'Gold-Inlay Zahn 16 präpariert und eingesetzt.',
        service: 'Inlay',
    },
    {
        kartei_id: 1016,
        entry_date: new Date('2024-05-07'),
        patient_id: 'P006',
        insurance_state: 'GKV',
        file_entry: 'PZR mit Politur.',
        service: 'PZR',
    },
    {
        kartei_id: 1017,
        entry_date: new Date('2024-05-14'),
        patient_id: 'P007',
        insurance_state: 'PKV',
        file_entry: 'Füllung Klasse II an Zahn 26.',
        service: 'Füllung',
    },
    {
        kartei_id: 1018,
        entry_date: new Date('2024-05-21'),
        patient_id: 'P008',
        insurance_state: 'GKV',
        file_entry: 'Beratung Zahnersatz Oberkiefer.',
        service: 'Beratung',
    },
    {
        kartei_id: 1019,
        entry_date: new Date('2024-06-04'),
        patient_id: 'P009',
        insurance_state: 'PKV',
        file_entry: 'Röntgen Einzelzahnaufnahme Zahn 11.',
        service: 'Röntgen',
    },
    {
        kartei_id: 1020,
        entry_date: new Date('2024-06-11'),
        patient_id: 'P010',
        insurance_state: 'GKV',
        file_entry: 'Extraktion Zahn 14, stark kariös.',
        service: 'Extraktion',
    },
    {
        kartei_id: 1021,
        entry_date: new Date('2024-06-18'),
        patient_id: 'P001',
        insurance_state: 'GKV',
        file_entry: 'Routinekontrolle, Mundhygiene gut.',
        service: 'Kontrolle',
    },
    {
        kartei_id: 1022,
        entry_date: new Date('2024-07-02'),
        patient_id: 'P002',
        insurance_state: 'PKV',
        file_entry: 'Inlay Keramik Zahn 24 neu angefertigt.',
        service: 'Inlay',
    },
    {
        kartei_id: 1023,
        entry_date: new Date('2024-07-16'),
        patient_id: 'P003',
        insurance_state: 'GKV',
        file_entry: 'PZR halbjährlich.',
        service: 'PZR',
    },
    {
        kartei_id: 1024,
        entry_date: new Date('2024-08-06'),
        patient_id: 'P004',
        insurance_state: 'GKV',
        file_entry: 'Füllung Zahn 36 nach erneuter Karies.',
        service: 'Füllung',
    },
    {
        kartei_id: 1025,
        entry_date: new Date('2024-08-20'),
        patient_id: 'P005',
        insurance_state: 'PKV',
        file_entry: 'Abschlusskontrolle nach Implantatversorgung.',
        service: 'Kontrolle',
    },
];
